CREATE DATEBASE taskforce
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci

USE taskforce

CREATE TABLE category (
  id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(256) NOT NULL,
  code VARCHAR(256) NOT NULL
);

CREATE TABLE task (
  id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(256) NOT NULL,
  description TEXT NOT NULL,
  dt_add DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  dt_end DATETIME NOT NULL,
  category_id INT(11) UNSIGNED NOT NULL,
  FOREIGN KEY (category_id) REFERENCES category (id) ON DELETE CASCADE,
  user_id INT(11) UNSIGNED NOT NULL,
  FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE,
  location_id INT(11) UNSIGNED NOT NULL,
  FOREIGN KEY (location_id) REFERENCES location (id) ON DELETE CASCADE,
  image VARCHAR(256) NOT NULL,
  price INT(6) NOT NULL,
  status ENUM('new', 'cancelled', 'in work', 'done', 'failed') NOT NULL DEFAULT('new')
);

CREATE TABLE user (
  id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  dt_add DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  name VARCHAR(256) NOT NULL,
  email VARCHAR(256) NOT NULL UNIQUE,
  password VARCHAR(256) NOT NULL UNIQUE,
  avatar VARCHAR(256) NOT NULL,
  birthday DATE NOT NULL,
  telephone VARCHAR(25) NOT NULL,
  telegram VARCHAR(64) NOT NULL,
  description TEXT,
  location_id INT(11) UNSIGNED NOT NULL,
  FOREIGN KEY (location_id) REFERENCES location (id) ON DELETE CASCADE,
  category_id INT(11) UNSIGNED NOT NULL,
  FOREIGN KEY (category_id) REFERENCES category (id) ON DELETE CASCADE,
  role ENUM('customer', 'contractor') NOT NULL
);

CREATE TABLE location (
  id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  town VARCHAR(256),
  lat DECIMAL NOT NULL,
  lng DECIMAL NOT NULL
);

CREATE TABLE response (
  id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  dt_add DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  user_id INT(11) UNSIGNED NOT NULL,
  FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE,
  task_id INT(11) UNSIGNED NOT NULL,
  FOREIGN KEY (task_id) REFERENCES task (id) ON DELETE CASCADE,
  content TEXT NOT NULL,
  price INT(6) NOT NULL,
  grade INT(1) NOT NULL
);
