CREATE DATEBASE taskforce
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci

USE taskforce

CREATE TABLE categories (
  id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name CHAR(15) NOT NULL,
  code CHAR(15) NOT NULL
);

CREATE TABLE tasks (
  id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  title CHAR(70) NOT NULL,
  description TEXT NOT NULL,
  dt_add DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  dt_end DATETIME NOT NULL,
  category_id INT(11) UNSIGNED NOT NULL,
  user_id INT(11) UNSIGNED NOT NULL,
  location_id INT(11) UNSIGNED NOT NULL,
  image CHAR(128) NOT NULL,
  price INT(6) NOT NULL,
  status CHAR(25) NOT NULL
);

CREATE TABLE users (
  id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  dt_add DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  name CHAR(100) NOT NULL,
  email CHAR(60) NOT NULL UNIQUE,
  password CHAR(32) NOT NULL UNIQUE,
  avatar CHAR(128) NOT NULL,
  birthday VARCHAR(10) NOT NULL,
  telephone VARCHAR(11) NOT NULL,
  telegram CHAR(64) NOT NULL,
  description TEXT,
  location_id INT(11) UNSIGNED NOT NULL,
  category_id INT(11) UNSIGNED NOT NULL,
  role CHAR(11) NOT NULL
);

CREATE TABLE location (
  id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  town CHAR(64),
  lat DECIMAL NOT NULL,
  lng DECIMAL NOT NULL
);

CREATE TABLE response (
  id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  dt_add DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  user_id INT(11) UNSIGNED NOT NULL,
  task_id INT(11) UNSIGNED NOT NULL,
  content TEXT NOT NULL,
  price INT(6) NOT NULL,
  grade INT(1) NOT NULL
);
